### ISSUE TITLE
Data access token

### ISSUE THREAD

**Issue by SreeramGanji** [Open-Speech-EkStep/wav2vec-infer#1]
While downloading the models using the below command,
gsutil -m cp -r gs://ekstepspeechrecognition-dev/deployed_models . 

It says 
"
     does not have storage.objects.list access to the Google Cloud Storage bucket.
"

Can you please provide list access for recursive access of the above command.

**Comment by harveenchadha** [comment]
@SreeramGanji This is a private bucket, please generate the custom model as per #2 .
